language: python
addons:
  postgresql: "9.3"
python:
- '2.7'
install:
- "pip install -U pip"
- "pip install setuptools==0.8"
- "pip install setuptools_git==1.1"
- "pip install -r requirements.txt"
- "pip install -e ."
before_script:
  - psql -c "create database torque_engine_test ENCODING 'UTF8' TEMPLATE template0;" -U postgres
script:
- nosetests src
